/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculator;

/**
 *
 * @author ferdiyansyah
 */
public class Calculator2 extends javax.swing.JFrame {

    /**
     * Creates new form Calculator2
     */
    private double angka1, jumlah;
    private int pilih;
    public Calculator2() {
        initComponents();
        buttonGroup1.add(on);
        buttonGroup1.add(off);
        on.setEnabled(false);
        on.setSelected(true);
    }
    
    
    public void enable(){
        display.setEnabled(true);
        
        on.setEnabled(false);
        off.setEnabled(true);
        
        tujuh.setEnabled(true);
        delapan.setEnabled(true);
        sembilan.setEnabled(true);
        tambah.setEnabled(true);
        empat.setEnabled(true);
        lima.setEnabled(true);
        enam.setEnabled(true);
        kurang.setEnabled(true);
        satu.setEnabled(true);
        dua.setEnabled(true);
        tiga.setEnabled(true);
        kali.setEnabled(true);
        nol.setEnabled(true);
        dnol.setEnabled(true);
        bagi.setEnabled(true);
        exit.setEnabled(true);
        plusminus.setEnabled(true);
        clear.setEnabled(true);
        samadengan.setEnabled(true);
        hapus.setEnabled(true);
        titik.setEnabled(true);
        log.setEnabled(true);
        pangkat.setEnabled(true);
        
    }
    
    public void disable(){
        display.setEnabled(false);
        
        on.setEnabled(true);
        off.setEnabled(false);

        tujuh.setEnabled(false);
        delapan.setEnabled(false);
        sembilan.setEnabled(false);
        tambah.setEnabled(false);
        empat.setEnabled(false);
        lima.setEnabled(false);
        enam.setEnabled(false);
        kurang.setEnabled(false);
        satu.setEnabled(false);
        dua.setEnabled(false);
        tiga.setEnabled(false);
        kali.setEnabled(false);
        nol.setEnabled(false);
        dnol.setEnabled(false);
        bagi.setEnabled(false);
        exit.setEnabled(false);
        plusminus.setEnabled(false);
        clear.setEnabled(false);
        samadengan.setEnabled(false);
        hapus.setEnabled(false);
        titik.setEnabled(false);
        log.setEnabled(false);
        pangkat.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        display = new javax.swing.JTextField();
        tujuh = new javax.swing.JButton();
        delapan = new javax.swing.JButton();
        sembilan = new javax.swing.JButton();
        tambah = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        empat = new javax.swing.JButton();
        lima = new javax.swing.JButton();
        enam = new javax.swing.JButton();
        kurang = new javax.swing.JButton();
        samadengan = new javax.swing.JButton();
        satu = new javax.swing.JButton();
        dua = new javax.swing.JButton();
        tiga = new javax.swing.JButton();
        kali = new javax.swing.JButton();
        bagi = new javax.swing.JButton();
        nol = new javax.swing.JButton();
        dnol = new javax.swing.JButton();
        titik = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        plusminus = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        label = new javax.swing.JLabel();
        on = new javax.swing.JRadioButton();
        off = new javax.swing.JRadioButton();
        log = new javax.swing.JButton();
        pangkat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ferdiyansyah Calculator");
        setLocation(new java.awt.Point(700, 250));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        display.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(display, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 280, 60));

        tujuh.setText("7");
        tujuh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tujuhActionPerformed(evt);
            }
        });
        getContentPane().add(tujuh, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 80, 70));

        delapan.setText("8");
        delapan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delapanActionPerformed(evt);
            }
        });
        getContentPane().add(delapan, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 80, 70));

        sembilan.setText("9");
        sembilan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sembilanActionPerformed(evt);
            }
        });
        getContentPane().add(sembilan, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 80, 70));

        tambah.setText("+");
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });
        getContentPane().add(tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 80, 70));

        clear.setText("C");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, 80, 70));

        empat.setText("4");
        empat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empatActionPerformed(evt);
            }
        });
        getContentPane().add(empat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 80, 70));

        lima.setText("5");
        lima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limaActionPerformed(evt);
            }
        });
        getContentPane().add(lima, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 80, 70));

        enam.setText("6");
        enam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enamActionPerformed(evt);
            }
        });
        getContentPane().add(enam, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 80, 70));

        kurang.setText("-");
        kurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kurangActionPerformed(evt);
            }
        });
        getContentPane().add(kurang, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 80, 70));

        samadengan.setText("=");
        samadengan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                samadenganActionPerformed(evt);
            }
        });
        getContentPane().add(samadengan, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 340, 80, 130));

        satu.setText("1");
        satu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                satuActionPerformed(evt);
            }
        });
        getContentPane().add(satu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 80, 70));

        dua.setText("2");
        dua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duaActionPerformed(evt);
            }
        });
        getContentPane().add(dua, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 80, 70));

        tiga.setText("3");
        tiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tigaActionPerformed(evt);
            }
        });
        getContentPane().add(tiga, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 80, 70));

        kali.setText("*");
        kali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kaliActionPerformed(evt);
            }
        });
        getContentPane().add(kali, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 80, 70));

        bagi.setText("/");
        bagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bagiActionPerformed(evt);
            }
        });
        getContentPane().add(bagi, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, 80, 70));

        nol.setText("0");
        nol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nolActionPerformed(evt);
            }
        });
        getContentPane().add(nol, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 80, 70));

        dnol.setText("00");
        dnol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dnolActionPerformed(evt);
            }
        });
        getContentPane().add(dnol, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 80, 70));

        titik.setText(".");
        titik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titikActionPerformed(evt);
            }
        });
        getContentPane().add(titik, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, 80, 70));

        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 170, 50));

        plusminus.setText("+/-");
        plusminus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusminusActionPerformed(evt);
            }
        });
        getContentPane().add(plusminus, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 420, 170, 50));

        hapus.setText("<--");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        getContentPane().add(hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 90, 60));
        getContentPane().add(label, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, -1, -1));

        on.setText("On");
        on.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onActionPerformed(evt);
            }
        });
        getContentPane().add(on, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        off.setText("Off");
        off.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                offActionPerformed(evt);
            }
        });
        getContentPane().add(off, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        log.setText("Log");
        log.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logActionPerformed(evt);
            }
        });
        getContentPane().add(log, new org.netbeans.lib.awtextra.AbsoluteConstraints(359, 180, 80, 70));

        pangkat.setText("X^Y");
        pangkat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pangkatActionPerformed(evt);
            }
        });
        getContentPane().add(pangkat, new org.netbeans.lib.awtextra.AbsoluteConstraints(359, 260, 80, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tujuhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tujuhActionPerformed
        display.setText(display.getText()+"7");
    }//GEN-LAST:event_tujuhActionPerformed

    private void delapanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delapanActionPerformed
        display.setText(display.getText()+"8");
    }//GEN-LAST:event_delapanActionPerformed

    private void sembilanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sembilanActionPerformed
        display.setText(display.getText()+"9");
    }//GEN-LAST:event_sembilanActionPerformed

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
       angka1 = Double.parseDouble(display.getText());

       display.setText("");
       pilih = 1;
       label.setText(angka1 + "+");
    }//GEN-LAST:event_tambahActionPerformed

    private void empatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empatActionPerformed
        display.setText(display.getText()+"4");
    }//GEN-LAST:event_empatActionPerformed

    private void limaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limaActionPerformed
        display.setText(display.getText()+"5");
    }//GEN-LAST:event_limaActionPerformed

    private void enamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enamActionPerformed
        display.setText(display.getText()+"6");
    }//GEN-LAST:event_enamActionPerformed

    private void satuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_satuActionPerformed
        display.setText(display.getText()+"1");
    }//GEN-LAST:event_satuActionPerformed

    private void duaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duaActionPerformed
        display.setText(display.getText()+"2");
    }//GEN-LAST:event_duaActionPerformed

    private void tigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tigaActionPerformed
        display.setText(display.getText()+"3");
    }//GEN-LAST:event_tigaActionPerformed

    private void nolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nolActionPerformed
        display.setText(display.getText()+"0");
    }//GEN-LAST:event_nolActionPerformed

    private void dnolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dnolActionPerformed
        display.setText(display.getText()+"00");
    }//GEN-LAST:event_dnolActionPerformed

    private void kurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kurangActionPerformed
       angka1 = Double.parseDouble(display.getText());

       display.setText("");
       pilih = 2;
       label.setText(angka1 + "-");
    }//GEN-LAST:event_kurangActionPerformed

    private void kaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kaliActionPerformed
       angka1 = Double.parseDouble(display.getText());

       display.setText("");
       pilih = 3;
       label.setText(angka1 + "*");
    }//GEN-LAST:event_kaliActionPerformed

    private void bagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bagiActionPerformed
       angka1 = Double.parseDouble(display.getText());

       display.setText("");
       pilih = 4;
       label.setText(angka1 + "/");
    }//GEN-LAST:event_bagiActionPerformed

    private void titikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titikActionPerformed
        display.setText(display.getText()+".");
    }//GEN-LAST:event_titikActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        display.setText("");
        label.setText("");
    }//GEN-LAST:event_clearActionPerformed

    private void plusminusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusminusActionPerformed
        display.setText(display.getText()+("-"));
    }//GEN-LAST:event_plusminusActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void samadenganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_samadenganActionPerformed
        switch(pilih) {
            case 1:
                jumlah = angka1 + Double.parseDouble(display.getText());
                label.setText(Double.toString(angka1)+ " + " 
                        +Double.parseDouble(display.getText()) + " = " + Double.toString(jumlah));
                display.setText(Double.toString(jumlah));
                
                break;
            case 2:
                jumlah = angka1 - Double.parseDouble(display.getText());
                label.setText(Double.toString(angka1)+ " - " 
                        +Double.parseDouble(display.getText()) + " = " + Double.toString(jumlah));
                display.setText(Double.toString(jumlah));
                break;
            case 3:
                jumlah = angka1 * Double.parseDouble(display.getText());
                label.setText(Double.toString(angka1)+ " * " 
                        +Double.parseDouble(display.getText()) + " = " + Double.toString(jumlah));
                display.setText(Double.toString(jumlah));
                break;
            case 4:
               jumlah = angka1 / Double.parseDouble(display.getText());
               label.setText(Double.toString(angka1)+ " / " 
                        +Double.parseDouble(display.getText()) + " = " + Double.toString(jumlah));
                display.setText(Double.toString(jumlah));
                break;
            case 5:
                jumlah = Math.log10(angka1);
                String answer = String.format("%,.6f", jumlah);
                label.setText("Log" + Double.toString(angka1) + " = " + answer);
                display.setText(answer);
                break; 
            case 6:
                jumlah = Math.pow(angka1,Double.parseDouble(display.getText()));
                label.setText(Double.toString(angka1)+ "^" 
                        +Double.parseDouble(display.getText()) + " = " + Double.toString(jumlah));
                display.setText(Double.toString(jumlah));
                break;
            default:             
                break;
        }
    }//GEN-LAST:event_samadenganActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        int length = display.getText().length();
        int number = display.getText().length() - 1;
        String store;
        
        if(length > 0){
            StringBuilder back = new StringBuilder(display.getText());
            back.deleteCharAt(number);
            store = back.toString();
            display.setText(store);
            label.setText(store);
        }
    }//GEN-LAST:event_hapusActionPerformed

    private void offActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_offActionPerformed
        disable();
        display.setText("");
    }//GEN-LAST:event_offActionPerformed

    private void onActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onActionPerformed
        enable();
    }//GEN-LAST:event_onActionPerformed

    private void logActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logActionPerformed
       angka1 = Double.parseDouble(display.getText());
       display.setText("Log"+ angka1);    
       pilih = 5;
       label.setText("Log" + angka1);
    }//GEN-LAST:event_logActionPerformed

    private void pangkatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pangkatActionPerformed
        angka1 = Double.parseDouble(display.getText());
        display.setText("");
        pilih = 6;
        label.setText(angka1 + "^");
    }//GEN-LAST:event_pangkatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bagi;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton clear;
    private javax.swing.JButton delapan;
    private javax.swing.JTextField display;
    private javax.swing.JButton dnol;
    private javax.swing.JButton dua;
    private javax.swing.JButton empat;
    private javax.swing.JButton enam;
    private javax.swing.JButton exit;
    private javax.swing.JButton hapus;
    private javax.swing.JButton kali;
    private javax.swing.JButton kurang;
    private javax.swing.JLabel label;
    private javax.swing.JButton lima;
    private javax.swing.JButton log;
    private javax.swing.JButton nol;
    private javax.swing.JRadioButton off;
    private javax.swing.JRadioButton on;
    private javax.swing.JButton pangkat;
    private javax.swing.JButton plusminus;
    private javax.swing.JButton samadengan;
    private javax.swing.JButton satu;
    private javax.swing.JButton sembilan;
    private javax.swing.JButton tambah;
    private javax.swing.JButton tiga;
    private javax.swing.JButton titik;
    private javax.swing.JButton tujuh;
    // End of variables declaration//GEN-END:variables
}
