/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package siswatable;

/**
 *
 * @author ferdiyansyah
 */
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class Mapel extends javax.swing.JFrame {
    private Connection con = null;
    private PreparedStatement pstmt = null;
    private ResultSet res = null;
    private DefaultTableModel tm = null;
    private String query = null;
    private final SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
    private boolean adaRecord = false;
    /**
     * Creates new form TabelMapel
     */
    public Mapel() {
        super("Ferdiyansyah");
        initComponents();
        con = koneksi.getConnection();
        query = "SELECT*FROM mapel order by kode";
        buttonGroup1.add(rbKode);
        buttonGroup1.add(rbMapel);
        buttonGroup1.add(rbKelompok);   
    }
    
    public Object[][] getAllMapel(){
        Object data[][] = null;
        try{
             pstmt = con.prepareStatement(query);
            if((rbKode.isSelected()) || (rbMapel.isSelected()) || (rbKelompok.isSelected())){
                pstmt.setString(1, "%"+filter.getText()+"%");
            }
            res = pstmt.executeQuery(); //eksekusi query hasilnya disimpan dalam res
            res.last(); //menju record terakhir
            int baris = res.getRow(); //mengambil no baris record terakhir
            res.beforeFirst(); //kembali ke sebelum record pertama
            data = new Object[baris][3]; //definisikan panjang array (baris, kolom)
            int i=0; //counter atau variabel pencacah
            while(res.next()){ //pengulangan selama masih ada record berikutnya
                data[i][0] = res.getString("kode");
                data[i][1] = res.getString("mapel");
                data[i][2] = res.getString("kelompok");
                i++;
            }
        }catch(SQLException e){
            System.err.println(e.getMessage());
        }
        return data;
    }
    
    public void tampil(){
        String[] judul = new String[] {"Kode Mapel","Mapel","Kelompok"};
        tm = new DefaultTableModel(getAllMapel(),judul);
        tabelMapel.setModel(tm);
    }
    
    public void hapus(){
        if(adaRecord){
            int pilih = JOptionPane.showConfirmDialog(null, "Data Mapel " 
                    + inMapel.getText() + " Akan dihapus?", "HAPUS MAPEL!",JOptionPane.YES_NO_OPTION);
            if(pilih == JOptionPane.YES_OPTION){
                String qry = "DELETE FROM mapel WHERE kode=?";
                try{
                    pstmt = con.prepareStatement(qry);
                    pstmt.setString(1, inKode.getText());
                    pstmt.executeUpdate();
                    tampil();
                    adaRecord = false;
                }catch(SQLException e){
                    System.err.println(e);
                }
            }
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        inTmplahir = new javax.swing.JTextField();
        inNisn = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        inGender = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        inTelepon = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        inTgllahir = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        inNis = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        inAlamat = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        inNama = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        rbNo = new javax.swing.JRadioButton();
        rbYes = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        inKelompok = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        inKode = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        inMapel = new javax.swing.JTextField();
        simpan = new javax.swing.JButton();
        hapus1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelMapel = new javax.swing.JTable();
        filter = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        rbKode = new javax.swing.JRadioButton();
        rbMapel = new javax.swing.JRadioButton();
        rbKelompok = new javax.swing.JRadioButton();

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Tanggal Lahir");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));
        jPanel2.add(inTmplahir, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 210, -1));
        jPanel2.add(inNisn, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, 160, -1));

        jLabel4.setText("Aktif");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, -1, -1));

        inGender.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "Laki-Laki", "Perempuan", " " }));
        jPanel2.add(inGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 130, -1));

        jLabel5.setText("Nama");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));
        jPanel2.add(inTelepon, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 160, 200, -1));

        jLabel6.setText("Gender");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));
        jPanel2.add(inTgllahir, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 140, -1));

        jLabel7.setText("Tempat Lahir");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        inNis.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inNisKeyReleased(evt);
            }
        });
        jPanel2.add(inNis, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 120, -1));

        jLabel8.setText("NIS");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        inAlamat.setColumns(20);
        inAlamat.setRows(5);
        jScrollPane3.setViewportView(inAlamat);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 60, 230, 90));

        jLabel9.setText("NISN");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, -1, -1));
        jPanel2.add(inNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 210, -1));

        jLabel10.setText("Alamat");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, -1, -1));

        jLabel11.setText("Telepon");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, -1, -1));

        rbNo.setText("NO");
        jPanel2.add(rbNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 210, -1, -1));

        rbYes.setText("YES");
        jPanel2.add(rbYes, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 210, -1, -1));

        jButton1.setText("SIMPAN");
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 250, -1, -1));

        hapus.setText("HAPUS");
        jPanel2.add(hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, -1, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(600, 150));
        setMinimumSize(new java.awt.Dimension(700, 720));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setText("DATA MAPEL");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel3.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 40));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 70));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inKelompok.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "Muatan Nasional", "Muatan Lokal", "Produktif RPL", "Produktif Tata Boga", "Produktif Tata Busana", "Produktif Perhotelan", "Produktif UPW" }));
        jPanel4.add(inKelompok, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 180, -1));

        jLabel14.setText("Mapel");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel15.setText("Kelompok");
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        inKode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inKodeKeyReleased(evt);
            }
        });
        jPanel4.add(inKode, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 120, -1));

        jLabel17.setText("Kode Mapel");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));
        jPanel4.add(inMapel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 210, -1));

        simpan.setText("SIMPAN");
        simpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                simpanMouseClicked(evt);
            }
        });
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });
        jPanel4.add(simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, -1, -1));

        hapus1.setText("HAPUS");
        hapus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapus1ActionPerformed(evt);
            }
        });
        jPanel4.add(hapus1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, -1, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 590, 240));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabelMapel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Kode Mapel", "Mapel", "Kelompok"
            }
        ));
        tabelMapel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMapelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelMapel);

        jScrollPane2.setViewportView(jScrollPane1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 530, 200));

        filter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterActionPerformed(evt);
            }
        });
        filter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                filterKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                filterKeyTyped(evt);
            }
        });
        jPanel1.add(filter, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 150, -1));

        jLabel1.setText("FILTER DATA");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        rbKode.setText("Kode Mapel");
        jPanel1.add(rbKode, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, -1, -1));

        rbMapel.setText("Mapel");
        rbMapel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMapelActionPerformed(evt);
            }
        });
        jPanel1.add(rbMapel, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, -1, -1));

        rbKelompok.setText("Kelompok");
        rbKelompok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbKelompokActionPerformed(evt);
            }
        });
        jPanel1.add(rbKelompok, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 590, 290));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void inNisKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inNisKeyReleased
        
    }//GEN-LAST:event_inNisKeyReleased

    private void inKodeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inKodeKeyReleased
        String qry = "SELECT*FROM mapel WHERE kode=?";
        try{
            pstmt = con.prepareStatement(qry);
            pstmt.setString(1, inKode.getText());
            res = pstmt.executeQuery();
            if(res.next()){
                inMapel.setText(res.getString("mapel"));
                if(res.getString("kelompok").equals("Muatan Nasional")){
                    inKelompok.setSelectedIndex(1);
                }else if(res.getString("kelompok").equals("Muatan Lokal")){
                    inKelompok.setSelectedIndex(2);
                }else if(res.getString("kelompok").equals("Produktif RPL")){
                    inKelompok.setSelectedIndex(3);
                }else if(res.getString("kelompok").equals("Produktif Tata Boga")){
                    inKelompok.setSelectedIndex(4);
                }else if(res.getString("kelompok").equals("Produktif Tata Busana")){
                    inKelompok.setSelectedIndex(5);
                }else if(res.getString("kelompok").equals("Produktif Perhotelan")){
                    inKelompok.setSelectedIndex(6);
                }else if(res.getString("kelompok").equals("Produktif UPW")){
                    inKelompok.setSelectedIndex(7);
                }
                adaRecord = true;
            }else{
                inMapel.setText("");
                inKelompok.setSelectedIndex(0);
                adaRecord = false;
            }
        }catch(SQLException e){
            System.err.println(e.getMessage());
        }
    }//GEN-LAST:event_inKodeKeyReleased

    private void tabelMapelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMapelMouseClicked
        inKode.setText(tm.getValueAt(tabelMapel.getSelectedRow(), 0).toString());
        inMapel.setText(tm.getValueAt(tabelMapel.getSelectedRow(), 1).toString());
        inKelompok.setSelectedItem(tm.getValueAt(tabelMapel.getSelectedRow(),2).toString());
    }//GEN-LAST:event_tabelMapelMouseClicked

    private void filterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filterActionPerformed

    private void filterKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_filterKeyReleased
        if(rbKode.isSelected()){
            query = "SELECT*FROM mapel WHERE kode LIKE ?";
        }else if(rbMapel.isSelected()){
            query = "SELECT*FROM mapel WHERE mapel LIKE ?";
        }else if(rbKelompok.isSelected()){
            query = "SELECT*FROM mapel WHERE kelompok LIKE ?";
        }else{
            query = "SELECT*FROM mapel ORDER BY kodemapel";
        }
        tampil();
    }//GEN-LAST:event_filterKeyReleased

    public void simpanData(){
        String qry;
        if(adaRecord){
            qry = "UPDATE mapel SET mapel=?, kelompok=? WHERE kode=?";         
        }else{
            qry = "INSERT INTO mapel (mapel, kelompok, kode) VALUES (?,?,?)";  
        }
        
        try{
            pstmt = con.prepareStatement(qry);
            pstmt.setString(1, inMapel.getText());
            pstmt.setString(2, inKelompok.getSelectedItem().toString());
            pstmt.setString(3, inKode.getText());
            pstmt.executeUpdate();
            tampil();
        }catch(SQLException e){
            System.err.println(e.getMessage());
        }
    }
    
    
    
    private void filterKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_filterKeyTyped

    }//GEN-LAST:event_filterKeyTyped

    private void rbMapelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMapelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbMapelActionPerformed

    private void rbKelompokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbKelompokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbKelompokActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        tampil();
    }//GEN-LAST:event_formWindowOpened

    private void simpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_simpanMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_simpanMouseClicked

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        if(inKode.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Kode Mapel harus diisi");
            inNis.requestFocus();
        }else if(inMapel.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Mapel harus diisi");
            inNama.requestFocus();
        }else{
          simpanData();  
          inKode.setText("");
        inMapel.setText("");
        inKelompok.setSelectedIndex(0);
        }
    }//GEN-LAST:event_simpanActionPerformed

    private void hapus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapus1ActionPerformed
        hapus();
        inKode.setText("");
        inMapel.setText("");
        inKelompok.setSelectedIndex(0);
    }//GEN-LAST:event_hapus1ActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        new Dashboard().setVisible(true);
        dispose();
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mapel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mapel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mapel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mapel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mapel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField filter;
    private javax.swing.JButton hapus;
    private javax.swing.JButton hapus1;
    private javax.swing.JTextArea inAlamat;
    private javax.swing.JComboBox inGender;
    private javax.swing.JComboBox inKelompok;
    private javax.swing.JTextField inKode;
    private javax.swing.JTextField inMapel;
    private javax.swing.JTextField inNama;
    private javax.swing.JTextField inNis;
    private javax.swing.JTextField inNisn;
    private javax.swing.JTextField inTelepon;
    private com.toedter.calendar.JDateChooser inTgllahir;
    private javax.swing.JTextField inTmplahir;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JRadioButton rbKelompok;
    private javax.swing.JRadioButton rbKode;
    private javax.swing.JRadioButton rbMapel;
    private javax.swing.JRadioButton rbNo;
    private javax.swing.JRadioButton rbYes;
    private javax.swing.JButton simpan;
    private javax.swing.JTable tabelMapel;
    // End of variables declaration//GEN-END:variables
}
