/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kasir;

/**
 *
 * @author ferdi
 */
public class index extends javax.swing.JFrame {

    /**
     * Creates new form index
     */
    String id;
    String nama;
    String level;
    
    public index(String iduser, String namauser, String role) {
        initComponents();
        nama = namauser;
        level = role;
        id = iduser;
        
        labelNama.setText(nama.toUpperCase());
        
        if(level.equals("administrator")){
            pesananMenu.setVisible(false);
//            transaksiMenu.setVisible(false);
        }else if(level.equals("waiter")){
            masterMenu.setVisible(false);
            mejaMenu.setVisible(false);
            barangMenu.setVisible(false);
        }else if(level.equals("kasir")){
            pesananMenu.setVisible(false);
            menuMenu.setVisible(false);
            masterMenu.setVisible(false);
            mejaMenu.setVisible(false);
            barangMenu.setVisible(false);
        }else if(level.equals("owner")){
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        labelNama = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        homeMenu = new javax.swing.JMenu();
        logout = new javax.swing.JMenuItem();
        masterMenu = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        menuMenu2 = new javax.swing.JMenuItem();
        mejaMenu = new javax.swing.JMenu();
        barangMenu = new javax.swing.JMenu();
        menuMenu = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        pesananMenu = new javax.swing.JMenu();
        Pesanan = new javax.swing.JMenuItem();
        Transaksi = new javax.swing.JMenuItem();
        logoutMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("SELAMAT DATANG");

        labelNama.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        labelNama.setText("jLabel2");

        homeMenu.setText("File   |");

        logout.setText("Logout");
        homeMenu.add(logout);

        jMenuBar1.add(homeMenu);

        masterMenu.setText("Master  |");

        jMenuItem1.setText("Pelanggan");
        masterMenu.add(jMenuItem1);

        jMenuItem2.setText("Meja");
        masterMenu.add(jMenuItem2);

        menuMenu2.setText("Menu");
        menuMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMenu2ActionPerformed(evt);
            }
        });
        masterMenu.add(menuMenu2);

        jMenuBar1.add(masterMenu);

        mejaMenu.setText("Meja   |");
        jMenuBar1.add(mejaMenu);

        barangMenu.setText("Barang   |");
        jMenuBar1.add(barangMenu);

        menuMenu.setText("Menu   |");
        menuMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMenuActionPerformed(evt);
            }
        });

        jMenu1.setText("jMenu1");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });
        menuMenu.add(jMenu1);

        jMenuBar1.add(menuMenu);

        pesananMenu.setText("Pesanan   |");

        Pesanan.setText("Pesanan");
        Pesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PesananActionPerformed(evt);
            }
        });
        pesananMenu.add(Pesanan);

        Transaksi.setText("Transaksi");
        pesananMenu.add(Transaksi);

        jMenuBar1.add(pesananMenu);

        logoutMenu.setText("Logout");
        jMenuBar1.add(logoutMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelNama)
                .addContainerGap(320, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(labelNama))
                .addContainerGap(317, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMenuActionPerformed
//        new menu(nama, level).setVisible(true);
//        dispose();
    }//GEN-LAST:event_menuMenuActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        new menu(nama, level).setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void menuMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMenu2ActionPerformed
        new menu(nama, level).setVisible(true);
        dispose();
    }//GEN-LAST:event_menuMenu2ActionPerformed

    private void PesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PesananActionPerformed
        new pesanan(id,nama, level).setVisible(true);
        dispose();
    }//GEN-LAST:event_PesananActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new index().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Pesanan;
    private javax.swing.JMenuItem Transaksi;
    private javax.swing.JMenu barangMenu;
    private javax.swing.JMenu homeMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JLabel labelNama;
    private javax.swing.JMenuItem logout;
    private javax.swing.JMenu logoutMenu;
    private javax.swing.JMenu masterMenu;
    private javax.swing.JMenu mejaMenu;
    private javax.swing.JMenu menuMenu;
    private javax.swing.JMenuItem menuMenu2;
    private javax.swing.JMenu pesananMenu;
    // End of variables declaration//GEN-END:variables
}
